name: 'release-it tagger action'
description: 'Given a repo with a valid VERSION file, increment the version based on calver standards.'
inputs:
  github-ref:
    description: 'Github branch used to check for the correct pre-release tag'
    required: false
  dev-branch:
    description: 'Github branch associated with the development environment'
    default: dev
    required: false
  stage-branch:
    description: 'Github branch associated with the stage environment'
    default: stage
    required: false
  prod-branch:
    description: 'Github branch associated with the production environment'
    default: prod
    required: false
outputs:
  version:
    description: 'The updated version'
runs:
  using: 'node12'
  main: 'dist/index.js'
