name: Release Action

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps and build
        run: npm ci && npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Get version
        id: version
        run: |
          version_file="VERSION"
          version=`cat "$version_file"`
          echo ::set-output name=version::"$version"
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          release_name: "Release ${{ steps.version.outputs.version }}"
