name: Release Action

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps and build
        run: npm ci && npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag new version
        id: tag
        uses: clevyr/release-it-tagger-action@v24.4.1
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.tag.outputs.version }}"
          release_name: "Release ${{ steps.tag.outputs.version }}"
