name: Release Action

on:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tag new version
        id: tag
        uses: clevyr/release-it-tagger-action@logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          build: npm ci && npm run build
#          github-release: true
